path: 'https://test-stand.gb.ru/gateway/login'
username: 'Monica Kunde V'
password: 'add9b80be1'
path_2: 'https://test-stand.gb.ru/api/posts'
title: 'owbed'
description: 'desteny'
content: 'qwertyuiop asdfghjkl zxcvbnm'